# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: NetelipUserBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
                username_parameter: _username
                password_parameter: _password
            logout:
                path:   /logout
                target: /login

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~

    encoders:
        Netelip\UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/user, roles: ROLE_ADMIN }
        - { path: ^/task/index, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/task/add, roles: ROLE_ADMIN }
        - { path: ^/task/edit, roles: ROLE_ADMIN }
        - { path: ^/task/view, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/task/delete, roles: ROLE_ADMIN }
        - { path: ^/task/custom, roles: ROLE_USER }
        - { path: ^/task/process, roles: ROLE_USER }