netelip_user_index:
    path:     /index
    defaults: { _controller: NetelipUserBundle:User:index }

netelip_user_add:
    path:     /add
    defaults: { _controller: NetelipUserBundle:User:add }

netelip_user_create:
    path:     /create
    defaults: { _controller: NetelipUserBundle:User:create }
    methods: POST

netelip_user_edit:
    path:     /edit/{id}
    defaults: { _controller: NetelipUserBundle:User:edit }

netelip_user_update:
    path:     /update/{id}
    defaults: { _controller: NetelipUserBundle:User:update }
    methods: [POST, PUT]

netelip_user_view:
    path:     /view/{id}
    defaults: { _controller: NetelipUserBundle:User:view }

netelip_user_delete:
    path:     /delete/{id}
    defaults: { _controller: NetelipUserBundle:User:delete }
    methods: [POST, DELETE]

netelip_user_redirect_add:
    path:     /create
    defaults:
        _controller: NetelipUserBundle:User:add
        path: /add
        permanent: true

netelip_user_redirect_edit:
    path:     /update/{id}
    defaults:
        _controller: NetelipUserBundle:User:edit
        path: /edit
        permanent: true

